apiVersion: v1
name: canal
description: Install Canal Network Plugin.
version: v3.13.3
appVersion: v3.13.3
home: https://www.projectcalico.org/
keywords:
  - canal
sources:
  - https://github.com/galal-hussein/rke2-charts
maintainers:
  - name: Rancher Labs
    email: charts@rancher.com
